-- @description Slava REAPER Test Suite
-- @version 1.0.2
-- @author Slava Logutin
-- @metapackage
-- @changelog
--   Publish a harmless Files tester status-message update for ReaPack workflow testing.
-- @about ../README.md
-- @provides
--   [main win64] test_Curl_Jobs.lua
--   [main win64] test_Files.lua
--   [main win64] test_docx.lua
--   [main win64] test_neurocast_auth.lua
--   [main darwin] test_Curl_Jobs.lua
--   [main darwin] test_Files.lua
--   [main darwin] test_docx.lua
--   [main darwin] test_neurocast_auth.lua
--   [win64] modules/*.lua
--   [darwin] modules/*.lua
--   [win64] bin/win/curl.exe
--   [win64] bin/win/7z.exe
--   [win64] bin/win/7z.dll
--   [win64] ../LICENSE > licenses/PROJECT-LICENSE.txt
--   [darwin] ../LICENSE > licenses/PROJECT-LICENSE.txt
--   [win64] ../THIRD_PARTY_NOTICES.md > licenses/THIRD_PARTY_NOTICES.md
--   [darwin] ../THIRD_PARTY_NOTICES.md > licenses/THIRD_PARTY_NOTICES.md
--   [win64] licenses/curl-COPYING.license > licenses/curl-COPYING.txt
--   [win64] licenses/zlib-LICENSE.license > licenses/zlib-LICENSE.txt
--   [win64] licenses/7-Zip-License.license > licenses/7-Zip-License.txt
--   [win64] licenses/Unicode-License.license > licenses/Unicode-License.txt
--   [darwin] licenses/Unicode-License.license > licenses/Unicode-License.txt
